server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01
    username: root
    password: dch
    type: com.alibaba.druid.pool.DruidDataSource
    #jsp支持
  mvc:
    view:
      prefix: /view/
      suffix: .jsp


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

